server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pmcore?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: T4Z690522zyl

mybatis:
  type-aliases-package: cn.edu.xjtu.stu.orangesoft.backdoor.bean
  mapper-locations: classpath:mapping/*Mapping.xml


